### ISSUE TITLE
Just wanted to say thanks

### ISSUE THREAD

**Issue by kthornbloom** [mdales/Fretboard-etching#5]
I know this project is ancient, and sorry for abusing the issue system, just wanted to say thanks, and this is awesome. I went to build one myself and found this version ready to go. Lots of calculators out there, not so many that produce laser ready SVG's.

**Comment by mdales** [comment]
Thank you @kthornbloom, I really appreciate the message! Would love to see what you do with this some day.

**Comment by kthornbloom** [comment]
@mdales I made this weird thing! https://www.youtube.com/watch?v=9ufJEs6pYgw&ab_channel=ThornbloomInstruments
